# Generated by Django 5.1.7 on 2025-04-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='area_location',
            field=models.CharField(default='listing.property.location', max_length=100),
        ),
    ]
