# Generated by Django 5.1.7 on 2025-04-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_area_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area_location',
            field=models.TextField(),
        ),
    ]
