# Generated by Django 5.1.7 on 2025-04-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_area_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='area_location',
        ),
    ]
