# Generated by Django 5.1.7 on 2025-04-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_area_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented')], default='Available', max_length=20),
        ),
    ]
