# Generated by Django 5.1.7 on 2025-04-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROPERTY_OWNER', 'Property Owner'), ('TENANT', 'Tenant')], default='TENANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyownerprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='university',
            field=models.CharField(max_length=255),
        ),
    ]
