# Generated by Django 5.1.7 on 2025-04-07 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyownerprofile',
            options={'verbose_name': 'Property Owner ', 'verbose_name_plural': 'Property Owners'},
        ),
        migrations.AlterField(
            model_name='propertyownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
