# Generated by Django 5.1.7 on 2025-04-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='property/property_documents/'),
        ),
    ]
