# Generated by Django 5.1.7 on 2025-04-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='property/documents/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='property/images/'),
        ),
    ]
