# Generated by Django 5.1.7 on 2025-04-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_document_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(default='', max_length=300),
        ),
    ]
