# Generated by Django 5.1.7 on 2025-04-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
